package org.example.Dao;

import org.example.Config.DatabaseConnectionFactory;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseSetupDao {

    public void setupDatabase() {
        try (Connection conn = DatabaseConnectionFactory.getConnection();
             Statement stmt = conn.createStatement()) {

            // Criar tabelas
            stmt.executeUpdate("CREATE TABLE usuarios (" +
                    "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "nome VARCHAR2(120) NOT NULL," +
                    "email VARCHAR2(120) NOT NULL UNIQUE" +
                    ")");

            stmt.executeUpdate("CREATE TABLE estoque (" +
                    "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "nome VARCHAR2(120) NOT NULL," +
                    "descricao VARCHAR2(255)," +
                    "categoria VARCHAR2(100)," +
                    "quantidade NUMBER NOT NULL CHECK (quantidade >= 0)," +
                    "localizacao VARCHAR2(50)," +
                    "data_entrada TIMESTAMP NOT NULL," +
                    "usuarioEntrada NUMBER REFERENCES usuarios(id)," +
                    "data_retirada TIMESTAMP," +
                    "usuarioRetirada NUMBER REFERENCES usuarios(id)" +
                    ")");

            System.out.println("Tabelas criadas com sucesso!");

            // Inserir usuários
            stmt.executeUpdate("INSERT INTO usuarios (nome, email) VALUES ('Dr. Ana Paula', 'ana.paula@hospital.com')");
            stmt.executeUpdate("INSERT INTO usuarios (nome, email) VALUES ('Enf. Bruno Santos', 'bruno.santos@hospital.com')");
            stmt.executeUpdate("INSERT INTO usuarios (nome, email) VALUES ('Tec. Carla Moura', 'carla.moura@hospital.com')");
            stmt.executeUpdate("INSERT INTO usuarios (nome, email) VALUES ('Bioq. Diego Almeida', 'diego.almeida@hospital.com')");
            stmt.executeUpdate("INSERT INTO usuarios (nome, email) VALUES ('Dr. Fernanda Luz', 'fernanda.luz@hospital.com')");
            stmt.executeUpdate("INSERT INTO usuarios (nome, email) VALUES ('Tec. Gabriel Pires', 'gabriel.pires@hospital.com')");
            stmt.executeUpdate("INSERT INTO usuarios (nome, email) VALUES ('Enf. Helena Duarte', 'helena.duarte@hospital.com')");
            stmt.executeUpdate("INSERT INTO usuarios (nome, email) VALUES ('Tec. Igor Martins', 'igor.martins@hospital.com')");
            stmt.executeUpdate("INSERT INTO usuarios (nome, email) VALUES ('Bioq. Juliana Reis', 'juliana.reis@hospital.com')");
            stmt.executeUpdate("INSERT INTO usuarios (nome, email) VALUES ('Enf. Lucas Rocha', 'lucas.rocha@hospital.com')");

            System.out.println("Usuários inseridos com sucesso!");

            // Inserir itens no estoque (apenas 2 exemplos para ilustrar)
            stmt.executeUpdate("INSERT INTO estoque (nome, descricao, categoria, quantidade, localizacao, data_entrada, usuarioEntrada)" +
                    " VALUES ('Luvas de Látex', 'Luvas descartáveis tamanho M', 'EPI', 500, 'Prateleira E1', TIMESTAMP '2025-01-10 08:30:00', 1)");

            stmt.executeUpdate("INSERT INTO estoque (nome, descricao, categoria, quantidade, localizacao, data_entrada, usuarioEntrada)" +
                    " VALUES ('Máscaras Cirúrgicas', 'Máscaras descartáveis tripla camada', 'EPI', 1000, 'Prateleira E2', TIMESTAMP '2025-01-11 09:15:00', 2)");

            System.out.println("Itens de estoque inseridos com sucesso!");

            conn.commit();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

